version: "3.7"

services:
  postgres:
    image: 'postgres:12.1'
    container_name: 'java-postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: diplom
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: narzullayevj999@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
  app:
    build: ./
    restart: always
    container_name: 'diplom-app'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_PASSWORD: postgres
      filepath: /files
      HOME_LOG: /app-log
    ports:
      - "8091:8091"
    depends_on:
      - postgres
      - zipkin
    command: --spring.profiles.active=prod
    networks:
      - spring
      - postgres

volumes:
  db-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge