version: '3'

services:
  postgres:
    image: 'postgres:12.1'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=diplom'

  app:
    build: ./
    container_name: 'diplom-app'
    ports:
      - "8091:8091"
