server:
  port: 9000

spring:
  application:
    name: EMAIL-SERVICE
  zipkin:
    base-url: http://localhost:9411
  mail:
    host: smtp.gmail.com
    port: 587
    username: narzullayevj999@gmail.com
    password: skhonozucksapmnw


eureka:
  instance:
    hostname: localhost
    metadataMap:
      instanceId: EMAIL-SERVICE
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
