server:
  port: 9091

spring:
  application:
    name: TELEGRAM-SERVICE
  zipkin:
    base-url: http://localhost:9411
eureka:
  instance:
    hostname: localhost
    metadataMap:
      instanceId: TELEGRAM-SERVICE
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true