
spring:
  application:
    name: Diplom
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  #db environment
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:diplom}?enabledTLSProtocols=TLSv1.2
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  ##Jpa & Hibernate config
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true

  main:
    allow-bean-definition-overriding: true
  messages:
    basename: i18n
  ##Jackson
  jackson:
    serialization:
      fail-on-empty-beans: false
  #File config
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
##Logging
logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
    templates: ERROR

path:
  file: ${filepath:D:\IdeaProjects\diplom\upload_files}
server:
  port: 8091




