server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  #  cloud:
  #    gateway:
  #      routes:
  #        - id: TELEGRAM-SERVICE
  #          uri: lb://TELEGRAM-SERVICE
  #          predicates:
  #            - Path=/api/v1/telegram/**
  #        - id: EMAIL-SERVICE
  #          uri: lb://EMAIL-SERVICE
  #          predicates:
  #            - Path=/api/v1/email/**

  zipkin:
    base-url: http://localhost:9411


eureka:
  instance:
    hostname: localhost
    metadataMap:
      instanceId: API-GATEWAY
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true






