spring:
  application:
    name: SERVICE-REGISTRY
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: true
  instance:
    appname: SERVICE-REGISTRY
    preferIpAddress: true
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/